### ISSUE TITLE
Error: MissingValue("rpc_url")  

### ISSUE THREAD

**Issue by peter-jim** [ronanyeah/solana-rust-examples#1]
Hi,I am very appreciate your work.i had encounter some problem. when I try to interactive with solana,I alway get

  Finished dev [unoptimized + debuginfo] target(s) in 0.17s                                                                                                                                           
     Running `target/debug/list_nfts`                                                                                                                                                                   
Error: MissingValue("rpc_url")

I already install CLI and start solana-test-validator and set localhost server. thank you

**Comment by ronanyeah** [comment]
You are missing the environment variables:
![image](https://github.com/ronanyeah/solana-rust-examples/assets/9598261/b82039fc-dae4-466e-8bff-a6fc2ce7f805)
